# Generated by Django 5.0.1 on 2024-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='lugar',
            field=models.CharField(choices=[('0', 'Interior'), ('1', 'Exterior')], max_length=30),
        ),
    ]
