# Generated by Django 5.0.1 on 2024-05-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camarero_app', '0001_initial'),
        ('restoManager_app', '0002_alter_mesa_lugar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesa',
            new_name='Ubicacion',
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'managed': True, 'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
