# Generated by Django 5.0.1 on 2024-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0003_rename_mesa_ubicacion_alter_ubicacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='lugar',
            field=models.CharField(max_length=30),
        ),
    ]
