# Generated by Django 5.0.1 on 2024-03-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restoManager_app', '0003_delete_serviejemplo_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('contiene_alcohol', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Camarero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alta_camarero', models.DateField()),
            ],
            options={
                'verbose_name': 'Camarero',
                'verbose_name_plural': 'Camareros',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(choices=[('0', 'Interior'), ('1', 'Exterior')], max_length=20)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Camarero_Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.camarero')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.mesa')),
            ],
            options={
                'verbose_name': 'Camarero_Mesa',
                'verbose_name_plural': 'Camarero_Mesas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio_Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.bebida')),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.camarero_mesa')),
            ],
            options={
                'verbose_name': 'Servicio_Barra',
                'verbose_name_plural': 'Servicio_Barras',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio_Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.camarero_mesa')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.plato')),
            ],
            options={
                'verbose_name': 'Servicio_Cocina',
                'verbose_name_plural': 'Servicio_Cocinas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
