# Generated by Django 5.0.1 on 2024-05-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0005_alter_ubicacion_lugar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camarero',
            table='camarero',
        ),
    ]
