# Generated by Django 5.0.1 on 2024-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0005_categoria_alter_bebida_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='plato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
