# Generated by Django 5.0.1 on 2024-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0006_alter_camarero_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bebida',
            table='bebida',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='plato',
            table='plato',
        ),
        migrations.AlterModelTable(
            name='plato_categoria',
            table='plato_categoria',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicacion',
        ),
    ]
