# Generated by Django 5.0.1 on 2024-05-18 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0007_alter_bebida_table_alter_categoria_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarero',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='camarero',
            name='fecha_alta_camarero',
        ),
        migrations.RemoveField(
            model_name='camarero',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='camarero',
            name='nombre',
        ),
        migrations.AddField(
            model_name='camarero',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
