# Generated by Django 5.0.1 on 2024-03-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0007_alter_plato_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato_categoria',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restoManager_app.plato'),
        ),
    ]
