# Generated by Django 5.0.1 on 2024-03-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0008_alter_plato_categoria_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato_categoria',
            name='numero_menu',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
