# Generated by Django 5.0.1 on 2024-04-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0010_plato_categoria_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
