# Generated by Django 5.0.1 on 2024-04-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoManager_app', '0011_bebida_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_barra',
            name='camarero_mesa',
        ),
        migrations.RemoveField(
            model_name='servicio_cocina',
            name='camarero_mesa',
        ),
        migrations.RemoveField(
            model_name='servicio_barra',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='servicio_cocina',
            name='plato',
        ),
        migrations.DeleteModel(
            name='Camarero_Mesa',
        ),
        migrations.DeleteModel(
            name='Servicio_Barra',
        ),
        migrations.DeleteModel(
            name='Servicio_Cocina',
        ),
    ]
