# Generated by Django 5.0.6 on 2024-05-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camarero_app', '0005_alter_camarero_mesa_camarero'),
        ('restoManager_app', '0013_remove_camarero_user_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camarero',
        ),
    ]
