# Generated by Django 5.0.1 on 2024-05-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camarero_app', '0003_alter_camarero_mesa_camarero_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camarero_mesa',
            table='camarero_mesa',
        ),
    ]
