# Generated by Django 5.0.6 on 2024-05-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarero_app', '0004_alter_camarero_mesa_table'),
        ('restoManager_app', '0013_remove_camarero_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camarero_mesa',
            name='camarero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restoManager_app.rol'),
        ),
    ]
