# Generated by Django 5.0.6 on 2024-05-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camarero_app', '0005_alter_camarero_mesa_camarero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camarero_mesa',
            old_name='camarero',
            new_name='rol',
        ),
    ]
