# Generated by Django 5.0.1 on 2024-05-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camarero_app', '0001_initial'),
        ('restoManager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.bebida')),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='camarero_app.camarero_mesa')),
            ],
            options={
                'verbose_name': 'Servicio_Barra',
                'verbose_name_plural': 'Servicio_Barras',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio_Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='camarero_app.camarero_mesa')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.plato')),
            ],
            options={
                'verbose_name': 'Servicio_Cocina',
                'verbose_name_plural': 'Servicio_Cocinas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
