# Generated by Django 5.0.1 on 2024-05-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicio_barra',
            table='servicio_barra',
        ),
        migrations.AlterModelTable(
            name='servicio_cocina',
            table='servicio_cocina',
        ),
    ]
