# Generated by Django 5.0.6 on 2024-05-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_app', '0002_alter_servicio_barra_table_and_more'),
        ('restoManager_app', '0012_rename_id_user_camarero_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_cocina',
            name='plato',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.plato'),
        ),
        migrations.AlterField(
            model_name='servicio_cocina',
            name='servido',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
