# Generated by Django 5.0.1 on 2024-04-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocina_app', '0002_remove_servicio_barra_bebida_and_more'),
        ('restoManager_app', '0012_remove_servicio_barra_camarero_mesa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camarero_Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.camarero')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.mesa')),
            ],
            options={
                'verbose_name': 'Camarero_Mesa',
                'verbose_name_plural': 'Camarero_Mesas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio_Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.bebida')),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cocina_app.camarero_mesa')),
            ],
            options={
                'verbose_name': 'Servicio_Barra',
                'verbose_name_plural': 'Servicio_Barras',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio_Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servido', models.BooleanField(default=False)),
                ('hora_dia', models.DateTimeField()),
                ('camarero_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cocina_app.camarero_mesa')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restoManager_app.plato')),
            ],
            options={
                'verbose_name': 'Servicio_Cocina',
                'verbose_name_plural': 'Servicio_Cocinas',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
