# Generated by Django 5.0.6 on 2024-05-22 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_app', '0003_alter_servicio_cocina_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_cocina',
            name='hora_dia',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 12, 45, 36, 793786)),
        ),
    ]
