# Generated by Django 5.0.6 on 2024-05-30 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_app', '0029_alter_servicio_barra_servido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_cocina',
            name='hora_dia',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 20, 25, 11, 62925, tzinfo=datetime.timezone.utc)),
        ),
    ]
